name: zdev images

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    paths:
      - "ops/devcontainer/**"

jobs:
  pr-smoke:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: cpu
            dockerfile: ops/devcontainer/Dockerfile.cpu
          - name: cuda-12.4
            dockerfile: ops/devcontainer/Dockerfile.cuda-12.4
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          provenance: false
          tags: tmp/zdev:${{ matrix.name }}

  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: cpu
            dockerfile: ops/devcontainer/Dockerfile.cpu
            latest: cpu
            release: cpu
          - name: cuda-12.4
            dockerfile: ops/devcontainer/Dockerfile.cuda-12.4
            latest: cuda
            release: cuda-12.4
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: meta
        run: |
          DATE=$(date +'%y.%m')
          SHA=${GITHUB_SHA::7}
          echo "release=v${DATE}-${SHA}" >> "${GITHUB_OUTPUT}"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          provenance: true
          sbom: true
          tags: |
            ghcr.io/wherewithai/zdev:${{ matrix.name }}
            ghcr.io/wherewithai/zdev:latest-${{ matrix.latest }}
            ghcr.io/wherewithai/zdev:${{ steps.meta.outputs.release }}-${{ matrix.release }}
