#!/usr/bin/env python3
"""Rules written in the notebook: export `#|snakerule` cells to `rules/<notebook>.smk`, included by the Snakefile.

CRAFT asked whether the Snakefile could be edited from a notebook. It can, one cell at a time: a code cell whose
first line is `#|snakerule` holds Snakemake syntax (a rule, a variable, an include) and is copied verbatim, in
notebook order, into `rules/<notebook stem>.smk` beside the Snakefile. The Snakefile includes that file:

    include: "rules/06-ee-trained-search-agent-tinker.smk"

so the notebook stays the seat of the rule and the Snakefile stays the record. Cells are not executed by the
kernel (Snakemake syntax is not Python); a leading `%%script true` or a raw cell type would do the same, but a
directive keeps the nbdev idiom. Run by `just solveit-export`, after the module export.

    python nbsnake.py <notebook.ipynb> [...]
"""
import json, sys
from pathlib import Path


def export(nb_path: Path) -> Path | None:
    nb = json.loads(nb_path.read_text())
    cells = [c for c in nb["cells"] if c["cell_type"] == "code" and "".join(c["source"]).lstrip().startswith("#|snakerule")]
    if not cells: return None
    out = nb_path.parent / "rules" / f"{nb_path.stem}.smk"; out.parent.mkdir(exist_ok=True)
    body = f"# AUTOGENERATED by .zetteldev/nbsnake.py from {nb_path.name}: edit the #|snakerule cells, not this file.\n\n"
    for c in cells:
        src = "".join(c["source"]).split("\n", 1)[1] if "\n" in "".join(c["source"]) else ""
        body += src.rstrip() + "\n\n"
    out.write_text(body); return out


if __name__ == "__main__":
    for p in sys.argv[1:]:
        r = export(Path(p)); print(f"{p}: {'-> ' + str(r) if r else 'no #|snakerule cells'}")
